# -*- coding: utf-8 -*-
"""Contenido del planificador: Islandia 2027, pareja, camper."""

META = {
    "titulo": "Islandia salvaje",
    "sub": "Seis maneras de recorrerla en junio de 2027",
    "pareja": "2 viajeros, 32 años · vehículo propio alquilado · naturaleza salvaje por encima de todo",
    "fecha_doc": "Preparado el 18 de agosto de 2026",
}

# ---------------------------------------------------------------- cuándo ir
VENTANAS = [
    {
        "id": "junio",
        "tag": "Recomendada",
        "titulo": "Segunda quincena de junio",
        "fechas": "17 – 28 de junio de 2027",
        "score": 95,
        "luz": "20 h 55 min de sol + crepúsculo permanente. Solsticio el 21 de junio: el día no se acaba.",
        "temp": "8–15 °C en costa, 2–10 °C en el interior. Noches sobre 5 °C.",
        "abierto": [
            "Carretera 1 y todas las secundarias asfaltadas, al 100 %",
            "F35 Kjölur (Hveravellir, Kerlingarfjöll): suele abrir entre finales de mayo y el 10 de junio",
            "F208 norte hasta Landmannalaugar: primeros días de junio en años normales",
            "F208 sur / Eldgjá y F206 Lakagígar: entre el 15 y el 30 de junio",
            "F26 Sprengisandur y F88/F910 Askja: última semana de junio o primeros de julio",
            "Barcos a Hornstrandir y ferry Baldur con horario de verano",
        ],
        "fauna": [
            "Frailecillos en plena cría en Látrabjarg, Dyrhólaey y Stórhöfði",
            "Pico de ballenas en Húsavík: jorobadas casi garantizadas, azules posibles",
            "Corderos, potros y charranes árticos por todas partes",
        ],
        "contras": [
            "Precios máximos: la camper y los refugios del Laugavegur son lo primero que se agota",
            "Las F más profundas (Askja, Sprengisandur, Kverkfjöll) pueden seguir cerradas si el invierno fue duro",
            "Mosquitos no picadores en Mývatn a reventar: red de cabeza obligatoria",
            "Dormir con luz de día: antifaz y cortinas opacas en la camper",
        ],
        "veredicto": "La ventana que abre más puertas del año. Con luz hasta la medianoche caben dos sitios más cada día sin correr, y es la única fecha de las dos en la que el interior es accesible con vehículo propio.",
    },
    {
        "id": "abril",
        "tag": "Alternativa",
        "titulo": "Justo después de Semana Santa",
        "fechas": "29 de marzo – 7 de abril de 2027 (Pascua: 28 de marzo)",
        "score": 45,
        "luz": "13 h 30 min al empezar, 14 h 40 min al terminar. Islandia va en GMT todo el año.",
        "temp": "−3 a +6 °C en costa, bajo cero y nieve en el interior. Vientos de 20 m/s frecuentes.",
        "abierto": [
            "Círculo Dorado, costa sur, Snæfellsnes y la mayor parte de la carretera 1",
            "Cierres temporales por tormenta casi cada semana, sobre todo en el norte y los fiordos del este",
            "Todas las pistas F cerradas: nada de Landmannalaugar, Kerlingarfjöll, Askja ni Þórsmörk por tu cuenta",
            "Westfjords al norte de Ísafjörður y Strandir: solo con 4x4 y partes cerradas",
            "Hornstrandir cerrado: los barcos no empiezan hasta junio",
        ],
        "fauna": [
            "Los frailecillos empiezan a llegar a mediados de abril: llegas justo antes",
            "Ballenas arrancando temporada en Húsavík (algunas salidas todavía desde Reykjavík)",
            "Sí es temporada de zorro ártico con pelaje de invierno en Hornstrandir (sin acceso por barco)",
        ],
        "contras": [
            "Se pierde el interior completo, que es justo lo más salvaje del país",
            "Los días cortos y el mal tiempo obligan a recortar la ruta sobre la marcha",
            "Cuevas de hielo naturales ya cerrando (solo Katla, artificial, todo el año)",
        ],
        "veredicto": "Sale entre un 30 y un 40 % más barata y hay mucha menos gente, y aún caben auroras. Pero con el objetivo de ver el máximo número de sitios pierde por mucho: unas 40 paradas de esta lista no existen en abril.",
    },
]

DURACION = [
    {"dias": "7–8", "km": "900–1.200", "que": "Círculo Dorado + costa sur hasta Jökulsárlón + Snæfellsnes, ida y vuelta",
     "nota": "Cómodo, sin conducir más de 3 h al día. Te quedas sin norte y sin interior.", "estado": "corto"},
    {"dias": "9", "km": "1.600–1.900", "que": "Lo que teníais pensado: la vuelta completa justa, o el sur con interior",
     "nota": "Funciona, pero obliga a elegir: o vuelta completa sin desvíos, o media isla con calma. 3–4 h de coche diarias.", "estado": "justo"},
    {"dias": "11", "km": "1.900–2.400", "que": "La vuelta completa más un bloque salvaje entero (interior o Westfjords)",
     "nota": "El punto dulce. Dos días de margen para tiempo malo y para repetir un sitio que os enamore.", "estado": "optimo"},
    {"dias": "13–14", "km": "2.600–3.200", "que": "Vuelta + Westfjords + interior, o vuelta con tres días de trekking",
     "nota": "Solo si podéis con el gasto: la camper en junio es el 45 % del presupuesto.", "estado": "largo"},
]

# ---------------------------------------------------------------- rutas
ROUTES = [
    {
        "id": "A", "slug": "fuego",
        "kicker": "Ruta A · Interior",
        "name": "Fuego interior",
        "claim": "Riolita, azufre y vados: el corazón deshabitado de la isla",
        "dias": 10, "km": 1520, "cond": "2 h 40 min / día",
        "vehiculo": "Camper 4x4 con pistas F permitidas",
        "dif": 4,
        "ventana": "A partir del 20 de junio para tenerlo todo abierto",
        "resumen": "La isla tiene un interior del tamaño de Extremadura sin una sola casa. Esta ruta renuncia al norte "
                   "y a los fiordos para meterse dentro: dos cordilleras geotermales, el cráter de Ljótipollur, "
                   "Landmannalaugar cuatro noches de camino y salida por Eldgjá hacia los glaciares del sur.",
        "porque": ["Los tres paisajes más raros del país (Kerlingarfjöll, Landmannalaugar, Lakagígar) en una sola línea",
                   "Baños termales salvajes casi todos los días",
                   "Dormís en campings de montaña con 4 vecinos, no con 400"],
        "sacrificas": ["Norte entero: Mývatn, Dettifoss, Húsavík", "Fiordos del este", "Snæfellsnes y Westfjords"],
        "aviso": "Vados reales en la F208 sur y en la F206 a Laki. Ninguna aseguradora cubre daños por agua: "
                 "si el nivel llega por encima de la mitad de la rueda, se da la vuelta y no se discute.",
        "dias_detalle": [
            {"d": 1, "t": "Aterrizaje y península de Reykjanes", "km": 95,
             "x": "Recoger la camper en Keflavík y no salir corriendo hacia Reykjavík. La península es un campo de lava joven: Brimketill, los fumarolos de Seltún, el lago Kleifarvatn y los campos de lava de Fagradalsfjall. Noche en Grindavík o Hveragerði.",
             "stops": ["brimketill", "seltun", "kleifarvatn", "fagradalsfjall"]},
            {"d": 2, "t": "Río caliente y Círculo Dorado exprés", "km": 235,
             "x": "Reykjadalur al amanecer: 3 km de subida hasta un río a 38 °C donde bañarse sin nadie. Por la tarde el Círculo Dorado a contracorriente (Gullfoss primero, Geysir después, Þingvellir al final) y entrada a la F35.",
             "stops": ["reykjadalur", "gullfoss", "geysir", "thingvellir"]},
            {"d": 3, "t": "Kerlingarfjöll y Hveradalir", "km": 55,
             "x": "Día sin apenas coche. El valle de Hveradalir es un anfiteatro de barro hirviendo entre montañas rosas; 12 km de sendero circular con vistas al Hofsjökull. Baño en el río templado de Kerlingarfjöll y noche en el camping de montaña.",
             "stops": ["kerlingarfjoll", "hveravellir"]},
            {"d": 4, "t": "Kjölur al sur y valle de Þjórsárdalur", "km": 160,
             "x": "Bajada por la F35 hasta Gullfoss y entrada al valle de Þjórsárdalur: Háifoss y Granni cayendo 122 m en paralelo, el jardín de lava de Gjáin y la granja vikinga de Stöng. Noche en Hrauneyjar, la última gasolinera antes del desierto.",
             "stops": ["haifoss", "gjain"]},
            {"d": 5, "t": "F208 norte hasta Landmannalaugar", "km": 90,
             "x": "El cañón de Sigöldugljúfur con su pared de cascadas, el cráter rojo de Ljótipollur y entrada a Landmannalaugar. Primer baño en el arroyo termal del campamento, con el campo de lava de Laugahraun al lado.",
             "stops": ["sigoldugljufur", "ljotipollur", "landmannalaugar"]},
            {"d": 6, "t": "Landmannalaugar a pie", "km": 0,
             "x": "Día completo de senderos: Bláhnjúkur (940 m, 2 h, la mejor panorámica de riolita del país), bajada por Grænagil y vuelta por Brennisteinsalda entre fumarolas amarillas. 10 km y 500 m de desnivel, y otro baño al volver.",
             "stops": ["blahnjukur", "landmannalaugar"]},
            {"d": 7, "t": "Eldgjá, Ófærufoss y opción Laki", "km": 145,
             "x": "F208 sur, la parte con vados, hasta la fisura de Eldgjá y la cascada de Ófærufoss. Si la F206 está abierta y el tiempo acompaña, desvío a los cráteres de Lakagígar, 130 conos cubiertos de musgo. Noche en Kirkjubæjarklaustur.",
             "stops": ["eldgja", "lakagigar", "langisjor"]},
            {"d": 8, "t": "Cañones y la primera lengua de hielo", "km": 175,
             "x": "Fjaðrárgljúfur temprano para tenerlo vacío, y Skaftafell el resto del día: Svartifoss entre columnas de basalto y subida al mirador de Sjónarnípa sobre el Skaftafellsjökull. Noche en el camping de Skaftafell o Svínafell.",
             "stops": ["fjadrargljufur", "svartifoss", "svinafellsjokull"]},
            {"d": 9, "t": "Múlagljúfur, icebergs y Vestrahorn", "km": 210,
             "x": "El cañón escondido de Múlagljúfur (2 h ida y vuelta, sin carteles), Fjallsárlón, Jökulsárlón con los icebergs y la playa de diamantes. Si queda cuerpo, hasta Stokksnes para el Vestrahorn con luz de medianoche.",
             "stops": ["mulagljufur", "fjallsarlon", "jokulsarlon", "diamondbeach", "vestrahorn"]},
            {"d": 10, "t": "Costa sur de vuelta y vuelo", "km": 355,
             "x": "Vík y Reynisfjara al amanecer, Dyrhólaey con frailecillos, Hjörleifshöfði, y el final con las cascadas: Skógafoss, Kvernufoss, Seljalandsfoss y Gljúfrabúi. Devolución en Keflavík.",
             "stops": ["reynisfjara", "dyrholaey", "hjorleifshofdi", "skogafoss", "kvernufoss", "seljalandsfoss", "gljufrabui"]},
        ],
        "recorte": "En 9 días: quitad el día de Kerlingarfjöll y entrad a Landmannalaugar por Hrauneyjar directamente.",
    },
    {
        "id": "B", "slug": "vuelta",
        "kicker": "Ruta B · Vuelta completa",
        "name": "La vuelta salvaje",
        "claim": "La carretera 1 entera en sentido antihorario, con los desvíos que casi nadie hace",
        "dias": 11, "km": 2380, "cond": "3 h 20 min / día",
        "vehiculo": "Camper 2WD suficiente (4x4 recomendable por viento y grava)",
        "dif": 3,
        "ventana": "Cualquier fecha de junio: no depende de pistas F",
        "resumen": "La opción de máximo número de sitios. Antihorario para llegar al sur, que es lo más concurrido, "
                   "con el cansancio ya pasado y la gente de los tours de un día ya fuera. Incluye el Círculo de "
                   "Diamante completo, Stuðlagil y dos fiordos del este que la mayoría se salta.",
        "porque": ["Cubre las cinco regiones costeras y los grandes hitos del país",
                   "Sentido antihorario: el norte con el sol de cara y el sur sin autobuses",
                   "Es la más flexible si el tiempo se pone feo: siempre hay plan B a 40 km"],
        "sacrificas": ["El interior: sin pistas F no hay Landmannalaugar ni Kerlingarfjöll", "Westfjords", "Días largos a pie"],
        "aviso": "El desvío a Seyðisfjörður cruza el paso de Fjarðarheiði a 620 m: en junio ya está abierto, "
                 "pero con niebla es una hora de curvas sin quitamiedos.",
        "dias_detalle": [
            {"d": 1, "t": "Keflavík, Hvalfjörður y Borgarnes", "km": 150,
             "x": "Salir del aeropuerto rodeando la bahía por el fiordo de Hvalfjörður en vez de por el túnel: mirador de Glymur, la cascada más alta accesible del oeste. Compra grande en el Bónus de Borgarnes y primera noche allí.",
             "stops": ["glymur", "ringroad"]},
            {"d": 2, "t": "Snæfellsnes de punta a punta", "km": 215,
             "x": "Focas en Ytri Tunga, la iglesia negra de Búðir, los acantilados de Arnarstapi y Lóndrangar, la playa de guijarros negros de Djúpalónssandur bajo el Snæfellsjökull, el faro de Svörtuloft y cierre en Kirkjufell.",
             "stops": ["ytritunga", "budir", "arnarstapi", "londrangar", "djupalonssandur", "snaefellsjokull", "svortuloft", "kirkjufell"]},
            {"d": 3, "t": "Península de Vatnsnes y Skagafjörður", "km": 260,
             "x": "Cañón de Kolugljúfur, el arco de Hvítserkur y la colonia de focas de Vatnsnes desde la orilla. Noche en Skagafjörður con baño en Grettislaug, una poza de piedra al borde del mar.",
             "stops": ["kolugljufur", "hvitserkur", "vatnsnes", "grettislaug"]},
            {"d": 4, "t": "Tröllaskagi y Akureyri", "km": 195,
             "x": "La península de Tröllaskagi por la costa: Hofsós y su piscina infinita, los túneles hasta Siglufjörður y el museo del arenque. Tarde en Akureyri, ducha decente y cena de verdad.",
             "stops": ["siglufjordur", "akureyri"]},
            {"d": 5, "t": "Goðafoss, Aldeyjarfoss y Mývatn", "km": 175,
             "x": "Goðafoss de mañana, desvío por la 842 hasta Aldeyjarfoss (basalto negro y agua turquesa, el mejor secreto del norte) y llegada a Mývatn: pseudocráteres de Skútustaðir, Dimmuborgir, Grjótagjá, Hverir y el cráter Víti de Krafla. Baño en Mývatn Nature Baths.",
             "stops": ["godafoss", "aldeyjarfoss", "myvatn", "dimmuborgir", "grjotagja", "hverir", "krafla"]},
            {"d": 6, "t": "Círculo de Diamante y ballenas", "km": 230,
             "x": "Dettifoss y Selfoss por la orilla este (carretera 864, más salvaje y con menos gente), el cañón de Ásbyrgi, las columnas retorcidas de Hljóðaklettar y salida a Húsavík para tres horas de avistamiento de ballenas en velero.",
             "stops": ["dettifoss", "selfoss_north", "asbyrgi", "hljodaklettar", "husavik"]},
            {"d": 7, "t": "Stuðlagil y el valle de Fljótsdalur", "km": 250,
             "x": "Cruce del páramo de Möðrudalur con vistas al Herðubreið, bajada al cañón de Stuðlagil por la orilla este (5 km a pie) y por la tarde Hengifoss con sus franjas rojas de arcilla. Baño al atardecer en Vök, con piscinas flotando en un lago.",
             "stops": ["studlagil", "hengifoss", "vok"]},
            {"d": 8, "t": "Seyðisfjörður o Stórurð, y fiordos del este", "km": 245,
             "x": "Elegid uno: la calle arcoíris de Seyðisfjörður con su cascada al fondo, o la caminata a Stórurð, unos bloques de roca entre lagunas turquesa bajo los Dyrfjöll. Luego la costa fiordo a fiordo hasta Djúpivogur, con el Búlandstindur enfrente.",
             "stops": ["seydisfjordur", "storurd", "mjoifjordur", "djupivogur"]},
            {"d": 9, "t": "Vestrahorn, glaciar y laguna", "km": 205,
             "x": "Stokksnes al amanecer con el Vestrahorn reflejado en la arena negra, Höfn para langosta, y el bloque grande: Fjallsárlón, Jökulsárlón y la playa de diamantes con luz de medianoche.",
             "stops": ["vestrahorn", "hofn", "fjallsarlon", "jokulsarlon", "diamondbeach"]},
            {"d": 10, "t": "Skaftafell, Múlagljúfur y Fjaðrárgljúfur", "km": 190,
             "x": "Caminata a Svartifoss y al mirador de Sjónarnípa, o crampones en el Svínafellsjökull con guía. Múlagljúfur de propina y Fjaðrárgljúfur ya de tarde, con el cañón vacío.",
             "stops": ["svartifoss", "svinafellsjokull", "mulagljufur", "fjadrargljufur"]},
            {"d": 11, "t": "Costa sur y vuelo", "km": 265,
             "x": "Reynisfjara y Dyrhólaey a primera hora, el avión de Sólheimasandur si os apetece el paseo, Skógafoss, Kvernufoss, Seljalandsfoss y Gljúfrabúi. Última parada en la piscina de Hveragerði y devolución.",
             "stops": ["reynisfjara", "dyrholaey", "solheimasandur", "skogafoss", "kvernufoss", "seljalandsfoss", "gljufrabui"]},
        ],
        "recorte": "En 9 días: fusionad los días 3 y 4 y saltad el día 8 (fiordos del este) yendo directos de Egilsstaðir a Höfn.",
    },
    {
        "id": "C", "slug": "fiordos",
        "kicker": "Ruta C · Noroeste",
        "name": "Los fiordos del oeste",
        "claim": "La Islandia que se quedó fuera de la carretera 1",
        "dias": 11, "km": 1980, "cond": "3 h / día en grava",
        "vehiculo": "Camper 4x4 alta (no hacen falta pistas F, pero sí grava y pendientes)",
        "dif": 4,
        "ventana": "Desde el 15 de junio, cuando arrancan los barcos a Hornstrandir",
        "resumen": "Los Westfjords se llevan el 3 % de los visitantes del país y la mitad de su costa. Aquí van con "
                   "Snæfellsnes de entrada, el ferry Baldur para ahorrar 300 km, los acantilados de Látrabjarg, "
                   "un día entero en la reserva deshabitada de Hornstrandir y la costa de Strandir de vuelta.",
        "porque": ["La mayor concentración de fauna: frailecillos a un metro, focas, zorro ártico",
                   "Hornstrandir es lo más parecido a estar solos en el Atlántico Norte",
                   "Piscinas geotermales al borde del mar sin ticket ni cola"],
        "sacrificas": ["Jökulsárlón y los glaciares del sur", "Mývatn y el norte", "El interior"],
        "aviso": "En los Westfjords se conduce a 40 km/h de media: pistas de grava con precipicio y sin quitamiedos. "
                 "Contad el doble de tiempo del que diga el GPS y reservad el ferry Baldur en cuanto abran ventas.",
        "dias_detalle": [
            {"d": 1, "t": "Keflavík y sur de Snæfellsnes", "km": 230,
             "x": "Directos al norte por Borgarnes. Focas en Ytri Tunga, iglesia negra de Búðir y acantilados de Arnarstapi con el arco de Gatklettur. Noche en Arnarstapi o Hellnar.",
             "stops": ["ytritunga", "budir", "arnarstapi", "londrangar"]},
            {"d": 2, "t": "Snæfellsjökull y ferry a los fiordos", "km": 130,
             "x": "Vuelta al glaciar por la costa oeste: Djúpalónssandur, el faro de Svörtuloft, cueva de lava de Vatnshellir y Kirkjufell con sus cascadas. Al mediodía, ferry Baldur de Stykkishólmur a Brjánslækur, 2 h 45 min por el Breiðafjörður.",
             "stops": ["djupalonssandur", "snaefellsjokull", "svortuloft", "kirkjufell", "berserkjahraun"]},
            {"d": 3, "t": "Látrabjarg y Rauðasandur", "km": 165,
             "x": "El acantilado de Látrabjarg, 14 km de pared y 440 m de caída, con frailecillos que dejan acercarse a menos de un metro. Bajada a la playa rosa de Rauðasandur con la marea baja. Noche en Patreksfjörður.",
             "stops": ["latrabjarg", "raudasandur", "storhofdi"]},
            {"d": 4, "t": "Dynjandi y camino a Ísafjörður", "km": 210,
             "x": "Dynjandi, 100 m de cascada en abanico con cinco saltos menores debajo, y la carretera de Arnarfjörður entre montañas planas. Parada en la piscina de Reykjafjarðarlaug y llegada a Ísafjörður.",
             "stops": ["dynjandi", "arnarfjordur", "isafjordur"]},
            {"d": 5, "t": "Hornstrandir, día completo", "km": 0,
             "x": "Barco desde Ísafjörður a Hesteyri o Veiðileysufjörður: reserva natural sin carreteras, sin habitantes y con zorros árticos que no huyen porque nunca se les ha cazado. 12–18 km de caminata según desembarco y recogida por la tarde.",
             "stops": ["hornstrandir", "hornbjarg", "arcticfox"]},
            {"d": 6, "t": "Bolungarvík, Súðavík y el gran fiordo", "km": 190,
             "x": "El museo pesquero de Ósvör, el centro del zorro ártico en Súðavík y el recorrido del Ísafjarðardjúp con parada en la piscina de Heydalur. Noche camino de Strandir.",
             "stops": ["isafjordur", "arcticfox"]},
            {"d": 7, "t": "Strandir: Djúpavík y Krossneslaug", "km": 175,
             "x": "La costa más solitaria del país: la fábrica de arenque abandonada de Djúpavík, la pista hasta Norðurfjörður y baño en Krossneslaug, una piscina de hormigón de 1954 con el Ártico rompiendo a diez metros.",
             "stops": ["djupavik", "krossneslaug"]},
            {"d": 8, "t": "Drangsnes, Hólmavík y Vatnsnes", "km": 265,
             "x": "Las tres bañeras calientes de Drangsnes al borde del mar, el museo de brujería de Hólmavík y salto a la península de Vatnsnes: focas en Hindisvík y el arco de Hvítserkur.",
             "stops": ["drangsnes", "vatnsnes", "hvitserkur"]},
            {"d": 9, "t": "Kolugljúfur y Borgarfjörður", "km": 220,
             "x": "Cañón de Kolugljúfur y bajada al oeste: Hraunfossar y Barnafoss saliendo del campo de lava, el manantial de Deildartunguhver y baño en Krauma. Cueva de lava de Víðgelmir con casco y linterna.",
             "stops": ["kolugljufur", "hraunfossar", "deildartunguhver", "vidgelmir"]},
            {"d": 10, "t": "Þingvellir, Geysir y Gullfoss", "km": 195,
             "x": "El Círculo Dorado ya de propina, entrando por la 550 si está abierta: Þingvellir entre las dos placas, Strokkur cada diez minutos y Gullfoss. Baño en el río caliente de Reykjadalur si queda tiempo.",
             "stops": ["thingvellir", "geysir", "gullfoss", "reykjadalur"]},
            {"d": 11, "t": "Reykjanes y vuelo", "km": 100,
             "x": "Última mañana en Reykjanes: Brimketill, Gunnuhver, Seltún y, si os lo queréis regalar, Blue Lagoon a 10 minutos del aeropuerto antes de devolver la camper.",
             "stops": ["brimketill", "seltun", "bluelagoon"]},
        ],
        "recorte": "En 9 días: quitad Strandir (días 7 y 8) y volved por la 60 directos a Borgarnes.",
    },
    {
        "id": "D", "slug": "apie",
        "kicker": "Ruta D · A pie",
        "name": "Cuatro días sin coche",
        "claim": "El Laugavegur de refugio en refugio, y el sur con lo que sobra",
        "dias": 11, "km": 1150, "cond": "1 h 50 min / día + 78 km a pie",
        "vehiculo": "Camper 2WD + autobús de montaña para entrar y salir",
        "dif": 5,
        "ventana": "Del 25 de junio en adelante: los refugios abren cuando abre la F208",
        "resumen": "Si lo que buscáis es naturaleza salvaje de verdad, la forma de tenerla es andando. El Laugavegur "
                   "cruza 55 km de desierto volcánico entre Landmannalaugar y Þórsmörk en cuatro etapas, con refugio "
                   "cada noche. El resto del viaje es la costa sur con calma y un día de glaciar.",
        "porque": ["Cuatro días seguidos dentro del paisaje, no mirándolo por la ventanilla",
                   "Landmannalaugar y Þórsmörk sin necesidad de 4x4 ni vados",
                   "Cuesta menos: menos días de camper y menos kilómetros de gasolina"],
        "sacrificas": ["Norte y este de la isla", "Westfjords", "Flexibilidad: las fechas del trek se fijan en otoño"],
        "aviso": "Los refugios de la Ferðafélag Íslands para el verano se abren a reserva en otoño y se agotan en "
                 "semanas. Sin refugio hay que llevar tienda y las plazas de acampada también se llenan. "
                 "Cruces de río a pie con agua a la rodilla y a 4 °C: sandalias y bastones.",
        "dias_detalle": [
            {"d": 1, "t": "Llegada, Reykjanes y logística", "km": 105,
             "x": "Recogida de camper, compra de la comida del trek en Reykjavík y tarde tranquila en Reykjanes o en la piscina de Hveragerði. Preparar dos mochilas y dejar el resto en la camper.",
             "stops": ["seltun", "brimketill", "campervan"]},
            {"d": 2, "t": "Subida a Landmannalaugar", "km": 130,
             "x": "Camper aparcada en Hella o Hvolsvöllur y autobús de montaña a Landmannalaugar. Tarde de aclimatación: vuelta al campo de lava de Laugahraun, Brennisteinsalda y baño en el arroyo caliente.",
             "stops": ["landmannalaugar", "hrafntinnusker"]},
            {"d": 3, "t": "Etapa 1: a Hrafntinnusker", "km": 0,
             "x": "12 km y 470 m de subida entre fumarolas y neveros permanentes, con obsidiana suelta por el suelo. Es la etapa más fría del trek: el refugio está a 1.050 m y puede nevar en junio.",
             "stops": ["hrafntinnusker", "blahnjukur"]},
            {"d": 4, "t": "Etapa 2: a Álftavatn", "km": 0,
             "x": "12 km de bajada con el descenso más bonito del recorrido: se abre el valle y aparece el lago Álftavatn con los glaciares detrás. Primer vado a pie en Grashagakvísl.",
             "stops": ["alftavatn"]},
            {"d": 5, "t": "Etapa 3: a Emstrur", "km": 0,
             "x": "15 km cruzando el desierto negro de Mælifellssandur, con el vado de Bláfjallakvísl y la vista al cañón de Markarfljótsgljúfur al llegar. Desvío corto al mirador del cañón antes de cenar.",
             "stops": ["emstrur"]},
            {"d": 6, "t": "Etapa 4: a Þórsmörk", "km": 0,
             "x": "16 km hasta el bosque de Þórsmörk, cruzando el Þröngá con agua a la rodilla. Subida final a Valahnúkur para ver de dónde venís, y noche en Básar o Langidalur.",
             "stops": ["thorsmork", "stakkholtsgja"]},
            {"d": 7, "t": "Salida a Hvolsvöllur y reencuentro con la camper", "km": 60,
             "x": "Autobús de montaña de vuelta cruzando el Krossá. Tarde de piscina, ropa limpia y cena caliente en Hvolsvöllur. Si estáis enteros, Seljalandsfoss y Gljúfrabúi al atardecer.",
             "stops": ["seljalandsfoss", "gljufrabui"]},
            {"d": 8, "t": "Costa sur sin prisa", "km": 130,
             "x": "Skógafoss y la subida por las escaleras hasta el arranque del Fimmvörðuháls, Kvernufoss escondido detrás del museo, el avión de Sólheimasandur, Dyrhólaey con frailecillos y Reynisfjara.",
             "stops": ["skogafoss", "fimmvorduhals", "kvernufoss", "solheimasandur", "dyrholaey", "reynisfjara"]},
            {"d": 9, "t": "Þakgil o Hjörleifshöfði y cañones", "km": 145,
             "x": "Mañana en Þakgil, un camping metido en un anfiteatro de roca al que se llega por 14 km de pista, o en la cueva de Hjörleifshöfði. Tarde en Fjaðrárgljúfur y noche cerca de Skaftafell.",
             "stops": ["thakgil", "hjorleifshofdi", "fjadrargljufur"]},
            {"d": 10, "t": "Glaciar y laguna", "km": 195,
             "x": "Caminata con crampones por el Svínafellsjökull con guía (3 h), Svartifoss por la tarde y cierre en Jökulsárlón y la playa de diamantes con luz de medianoche.",
             "stops": ["svinafellsjokull", "svartifoss", "jokulsarlon", "diamondbeach"]},
            {"d": 11, "t": "Vuelta al aeropuerto", "km": 385,
             "x": "Múlagljúfur si no lo hicisteis, y regreso pausado por la costa sur con las paradas que os faltasen. Devolución en Keflavík.",
             "stops": ["mulagljufur", "midnightsun"]},
        ],
        "recorte": "En 9 días: Laugavegur en 4 etapas y solo 3 días de costa sur, sin pasar de Skaftafell.",
    },
    {
        "id": "E", "slug": "clasica-sur",
        "kicker": "Clásica 1 · Ida y vuelta",
        "name": "Sur, Círculo Dorado y Snæfellsnes",
        "claim": "La primera vez que se va a Islandia, con poco coche y todos los iconos",
        "dias": 9, "km": 1280, "cond": "2 h 20 min / día",
        "vehiculo": "Camper 2WD o coche pequeño con hoteles",
        "dif": 1,
        "ventana": "Sirve en junio y también justo después de Semana Santa",
        "resumen": "La ruta que hace la mayoría, y no por casualidad: concentra las cascadas, los glaciares, las playas "
                   "negras y la península de Snæfellsnes en distancias cortas, sin grava y con servicios cada pocos "
                   "kilómetros. Es también la única de las seis que funciona igual de bien en abril.",
        "porque": ["Cero riesgo logístico y el mejor plan si el tiempo se pone en contra",
                   "Los iconos del país con margen para volver a un sitio dos veces",
                   "La más barata: camper 2WD y menos gasolina"],
        "sacrificas": ["Norte, este y Westfjords", "El interior", "La sensación de estar solos"],
        "aviso": "Es la zona con más gente del país. La forma de arreglarlo es el horario: los grandes hitos "
                 "antes de las 9 o después de las 19, que en junio sigue habiendo luz de sobra.",
        "dias_detalle": [
            {"d": 1, "t": "Llegada y Reykjanes", "km": 90,
             "x": "Camper en Keflavík, campos de lava de Fagradalsfjall, Brimketill, Gunnuhver y los colores de Seltún. Noche en Grindavík con opción de Blue Lagoon o Sky Lagoon.",
             "stops": ["fagradalsfjall", "brimketill", "seltun", "bluelagoon"]},
            {"d": 2, "t": "Círculo Dorado", "km": 240,
             "x": "Þingvellir andando por la grieta de Almannagjá, Strokkur, Gullfoss y el cráter de Kerið. Cierre con el río caliente de Reykjadalur o la piscina de Flúðir.",
             "stops": ["thingvellir", "geysir", "gullfoss", "kerid", "brudarfoss"]},
            {"d": 3, "t": "Cascadas de la costa sur", "km": 155,
             "x": "Seljalandsfoss por detrás del agua, Gljúfrabúi metida en su grieta, Skógafoss de frente y Kvernufoss casi en secreto. Tarde en Sólheimasandur y noche en Vík.",
             "stops": ["seljalandsfoss", "gljufrabui", "skogafoss", "kvernufoss", "solheimasandur"]},
            {"d": 4, "t": "Vík, Dyrhólaey y Reynisfjara", "km": 95,
             "x": "Frailecillos en Dyrhólaey a primera hora, columnas de basalto y Reynisdrangar en Reynisfjara, y por la tarde Hjörleifshöfði o la pista a Þakgil.",
             "stops": ["dyrholaey", "reynisfjara", "hjorleifshofdi", "thakgil"]},
            {"d": 5, "t": "Cañones, Skaftafell y glaciar", "km": 190,
             "x": "Fjaðrárgljúfur temprano, Svartifoss y el mirador de Sjónarnípa en Skaftafell, y caminata sobre el hielo del Svínafellsjökull con guía.",
             "stops": ["fjadrargljufur", "svartifoss", "svinafellsjokull"]},
            {"d": 6, "t": "Jökulsárlón y vuelta al oeste", "km": 220,
             "x": "Múlagljúfur, Fjallsárlón, Jökulsárlón en zodiac o desde la orilla y la playa de diamantes. Vuelta hacia el oeste con parada en Vík.",
             "stops": ["mulagljufur", "fjallsarlon", "jokulsarlon", "diamondbeach"]},
            {"d": 7, "t": "Al oeste: Borgarfjörður", "km": 265,
             "x": "Etapa de traslado con premio: Hraunfossar y Barnafoss, el manantial hirviendo de Deildartunguhver con baño en Krauma y la cueva de lava de Víðgelmir.",
             "stops": ["hraunfossar", "deildartunguhver", "vidgelmir"]},
            {"d": 8, "t": "Snæfellsnes completa", "km": 225,
             "x": "Kirkjufell, Djúpalónssandur, el faro de Svörtuloft, Lóndrangar, Arnarstapi y las focas de Ytri Tunga. Noche en Borgarnes o Hvalfjörður.",
             "stops": ["kirkjufell", "djupalonssandur", "svortuloft", "londrangar", "arnarstapi", "ytritunga", "snaefellsjokull"]},
            {"d": 9, "t": "Reykjavík y vuelo", "km": 105,
             "x": "Mañana en Reykjavík: Hallgrímskirkja, el puerto viejo y Sky Lagoon antes de devolver la camper en Keflavík.",
             "stops": ["skylagoon", "midnightsun"]},
        ],
        "recorte": "En 7 días: fuera los días 7 y 8 (oeste) y vuelo tras el Círculo Dorado.",
    },
    {
        "id": "F", "slug": "clasica-anillo",
        "kicker": "Clásica 2 · Vuelta rápida",
        "name": "La carretera 1 en nueve días",
        "claim": "La vuelta completa a la isla en el plazo que teníais pensado",
        "dias": 9, "km": 1780, "cond": "3 h 40 min / día",
        "vehiculo": "Camper 2WD",
        "dif": 3,
        "ventana": "Junio. En abril es posible pero con cierres frecuentes en el norte",
        "resumen": "La versión estándar del anillo: los hitos de cada región sin desvíos largos, en sentido horario "
                   "para tener el sur el primer día y el norte a mitad de viaje. Es la ruta con más kilómetros por "
                   "día de las seis, y funciona si aceptáis que cada sitio se ve una vez y se sigue.",
        "porque": ["Cumple los 9 días que teníais en mente sin dejar fuera ninguna región",
                   "Todo asfaltado y con gasolineras y campings cada 60-80 km",
                   "Es la más fácil de reservar: es lo que alquila todo el mundo"],
        "sacrificas": ["Los desvíos que hacen especial cada región", "Días a pie", "Margen si hay tormenta"],
        "aviso": "3 h 40 min de media al día es mucho para una camper con viento lateral. Repartíos la conducción "
                 "y no encadenéis dos etapas de más de 300 km.",
        "dias_detalle": [
            {"d": 1, "t": "Círculo Dorado", "km": 250,
             "x": "Þingvellir, Geysir, Gullfoss y Kerið directos desde el aeropuerto. Noche cerca de Hella o Hvolsvöllur.",
             "stops": ["thingvellir", "geysir", "gullfoss", "kerid"]},
            {"d": 2, "t": "Cascadas y playas negras", "km": 165,
             "x": "Seljalandsfoss, Gljúfrabúi, Skógafoss, Kvernufoss, Dyrhólaey y Reynisfjara. Noche en Vík.",
             "stops": ["seljalandsfoss", "gljufrabui", "skogafoss", "dyrholaey", "reynisfjara"]},
            {"d": 3, "t": "Cañones, Skaftafell e icebergs", "km": 250,
             "x": "Fjaðrárgljúfur, Svartifoss, Fjallsárlón, Jökulsárlón y la playa de diamantes. Noche en Höfn.",
             "stops": ["fjadrargljufur", "svartifoss", "jokulsarlon", "diamondbeach", "vestrahorn"]},
            {"d": 4, "t": "Fiordos del este", "km": 265,
             "x": "Vestrahorn al amanecer y la costa fiordo a fiordo hasta Egilsstaðir, con Djúpivogur y el Búlandstindur de fondo. Baño en Vök.",
             "stops": ["vestrahorn", "djupivogur", "vok"]},
            {"d": 5, "t": "Stuðlagil y Mývatn", "km": 280,
             "x": "Cañón de Stuðlagil por la mañana, cruce del páramo de Möðrudalur y llegada a Mývatn: Hverir, Krafla, Grjótagjá y Dimmuborgir.",
             "stops": ["studlagil", "hverir", "krafla", "grjotagja", "dimmuborgir", "myvatn"]},
            {"d": 6, "t": "Dettifoss, Ásbyrgi y ballenas", "km": 230,
             "x": "Dettifoss y Selfoss, el cañón de Ásbyrgi y salida de ballenas en Húsavík por la tarde. Noche en Húsavík o Akureyri.",
             "stops": ["dettifoss", "selfoss_north", "asbyrgi", "husavik"]},
            {"d": 7, "t": "Goðafoss, Akureyri y Skagafjörður", "km": 215,
             "x": "Goðafoss de camino, mañana en Akureyri y tarde por Tröllaskagi hasta Skagafjörður, con baño en Grettislaug.",
             "stops": ["godafoss", "akureyri", "siglufjordur", "grettislaug"]},
            {"d": 8, "t": "Hvítserkur, Kolugljúfur y Snæfellsnes", "km": 290,
             "x": "Hvítserkur y las focas de Vatnsnes, cañón de Kolugljúfur y llegada a Snæfellsnes para Kirkjufell al atardecer.",
             "stops": ["hvitserkur", "vatnsnes", "kolugljufur", "kirkjufell"]},
            {"d": 9, "t": "Snæfellsnes y vuelo", "km": 235,
             "x": "Djúpalónssandur, Arnarstapi y Ytri Tunga de mañana, y vuelta al aeropuerto por Borgarnes.",
             "stops": ["djupalonssandur", "arnarstapi", "ytritunga", "snaefellsjokull"]},
        ],
        "recorte": "Con 11 días: añadid Snæfellsnes al principio y un día completo en Mývatn y otro en el este.",
    },
]

# ---------------------------------------------------------------- logística
PRESUPUESTO = [
    ["Vuelos ida y vuelta (2 pers.)", "500 – 900 €", "Desde Barcelona o Madrid a Keflavík. Play, easyJet y Vueling en verano. Reservar ya: junio 2027 sube desde el otoño."],
    ["Camper 4x4 con pistas F, 10 días", "2.400 – 3.400 €", "Para las rutas A y C. Modelos tipo Duster o Hilux camperizados. Se agotan de febrero a marzo."],
    ["Camper 2WD 2 plazas, 10 días", "1.500 – 2.300 €", "Suficiente para B, D, E y F. Ojo: casi todos los contratos prohíben pistas F."],
    ["Combustible", "300 – 550 €", "Diésel sobre 2,10 – 2,40 €/l. Una camper gasta 9-11 l/100 km."],
    ["Campings, 9-10 noches", "300 – 420 €", "27 – 42 € por noche y pareja. La Camping Card (unos 180 €) cubre unos 40 campings y sale a cuenta desde 7 noches."],
    ["Comida de supermercado", "350 – 480 €", "Bónus y Krónan. Cocinar en la camper es lo que hace viable el viaje."],
    ["Restaurantes y cafés", "150 – 350 €", "Dos o tres cenas fuera y algún café. Un plato ronda 28-35 €."],
    ["Actividades", "400 – 800 €", "Ballenas en Húsavík 100-130 €/pers., glaciar con guía 100-120 €, barco a Hornstrandir 80-100 €, piscinas 10-20 €."],
    ["Ferry Baldur (solo ruta C)", "100 – 150 €", "Coche + 2 personas de Stykkishólmur a Brjánslækur."],
    ["Extras y colchón", "200 – 300 €", "Túnel de Vaðlaheiði, duchas, lavandería, gorros que se compran sobre la marcha."],
]

RESERVAS = [
    ["Ahora, agosto-septiembre 2026", "Vuelos", "Es lo que más sube. Fijad primero la ventana de fechas y comprad."],
    ["Septiembre-octubre 2026", "Camper", "Las 4x4 con pistas F permitidas son pocas. Si vais a la ruta A o C, esto va antes que cualquier otra cosa."],
    ["Octubre-noviembre 2026", "Refugios del Laugavegur", "La Ferðafélag Íslands abre el verano siguiente en otoño y se agota en semanas. Solo para la ruta D."],
    ["Enero-febrero 2027", "Ferry Baldur y barcos de Hornstrandir", "Horarios de verano publicados. Ruta C."],
    ["Marzo-abril 2027", "Ballenas, glaciar, Blue Lagoon", "Con dos meses basta, pero las salidas de las 9:00 se llenan."],
    ["Mayo 2027", "Camping Card y última revisión", "Comprad la tarjeta y revisad las fechas históricas de apertura de las pistas F en road.is."],
]

PRACTICO = [
    {"t": "Pistas F y vados",
     "x": "Solo con 4x4 real y con el contrato que lo permita por escrito. Ningún seguro cubre daños por agua en un vado: "
          "se cruza andando primero, se entra en primera larga, sin parar y siguiendo la diagonal de la corriente. Si el "
          "agua pasa de la mitad de la rueda, se da la vuelta."},
    {"t": "Viento",
     "x": "Es el peligro real, más que el hielo. Con rachas de más de 18 m/s una camper alta se vuelve incontrolable y "
          "abrir la puerta a favor del viento la arranca (daño no cubierto). Consultad vedur.is cada mañana."},
    {"t": "Dormir",
     "x": "Acampada libre prohibida desde 2015: solo campings. En junio el sol no se pone: antifaz, y aparcar mirando "
          "al norte para que no dé en la cara."},
    {"t": "Seguros",
     "x": "Coged grava (gravel), arena y ceniza (sand and ash) y cristales. Son los tres daños habituales. "
          "El resto suele ser humo."},
    {"t": "Aplicaciones",
     "x": "road.is o umferdin.is para estado de carreteras, vedur.is para viento y aviso naranja, safetravel.is para "
          "dejar el plan de ruta, y 112 Iceland para emergencias."},
    {"t": "Dinero y comida",
     "x": "Tarjeta para todo, no hace falta efectivo. Alcohol solo en Vínbúðin o en el duty free del aeropuerto al llegar, "
          "que es donde sale la mitad de precio."},
]

# ---------------------------------------------------------------- pies de foto
TAGS = {
 "thingvellir": "Grieta entre la placa americana y la europea, y el parlamento más antiguo del mundo",
 "geysir": "Strokkur revienta cada 8-10 minutos, hasta 25 m de columna",
 "gullfoss": "Dos saltos y 140 m³/s cayendo en un cañón de basalto",
 "kerid": "Cráter de 55 m con un lago verde dentro, 3.000 años",
 "brudarfoss": "Salto turquesa escondido a 1,5 km de la carretera",
 "seljalandsfoss": "60 m de caída con sendero por detrás de la cortina de agua",
 "gljufrabui": "Cascada metida en una grieta: se entra por el arroyo",
 "skogafoss": "25 m de ancho y arcoíris permanente cuando sale el sol",
 "kvernufoss": "La hermana vacía de Skógafoss, también se pasa por detrás",
 "dyrholaey": "Arco de roca de 120 m y colonia de frailecillos hasta agosto",
 "reynisfjara": "Arena negra, columnas de basalto y los farallones de Reynisdrangar",
 "hjorleifshofdi": "Antiguo islote hoy rodeado de arena negra, con la cueva de Yoda",
 "thakgil": "Camping en un anfiteatro de roca al final de 14 km de pista",
 "fjadrargljufur": "Cañón de 100 m de profundidad y 2 km de sendero por el borde",
 "svartifoss": "Cascada enmarcada por columnas hexagonales de basalto",
 "mulagljufur": "Cañón sin cartel ni aparcamiento, con la cascada de Hangandifoss",
 "fjallsarlon": "Laguna glaciar pequeña con el frente del Fjallsjökull a la vista",
 "jokulsarlon": "Icebergs desprendidos del Breiðamerkurjökull camino del mar",
 "diamondbeach": "El hielo de la laguna varado en arena negra",
 "vestrahorn": "454 m de gabro sobre la playa de Stokksnes",
 "hofn": "Puerto de la langosta y base para el sureste",
 "landmannalaugar": "Montañas de riolita de todos los colores y arroyo termal",
 "blahnjukur": "940 m de ceniza azul, dos horas y la mejor vista del interior",
 "ljotipollur": "Cráter de explosión con paredes rojas y lago dentro",
 "sigoldugljufur": "Pared de cascadas en fila sobre agua turquesa",
 "eldgja": "La mayor fisura volcánica del mundo, con la cascada de Ófærufoss",
 "langisjor": "Lago de 20 km entre montañas de musgo, sin una sola construcción",
 "lakagigar": "130 cráteres de la erupción de 1783, hoy tapizados de musgo",
 "hveravellir": "Campo geotermal en medio de la ruta de Kjölur, con poza de baño",
 "kerlingarfjoll": "Valle de Hveradalir: barro hirviendo entre montañas rosas",
 "haifoss": "122 m de caída, con Granni al lado en el mismo cañón",
 "gjain": "Pequeño valle de cascadas y columnas de lava, junto a la granja de Stöng",
 "thorsmork": "Valle entre tres glaciares, final del Laugavegur",
 "stakkholtsgja": "Cañón de 100 m que acaba en una cascada dentro de una cueva",
 "sprengisandur": "Doscientos kilómetros de desierto de ceniza entre dos glaciares",
 "askja": "Caldera con el lago Öskjuvatn y el cráter templado de Víti",
 "holuhraun": "Campo de lava de 2014, el mayor de Islandia en 200 años",
 "kverkfjoll": "Cuevas de hielo bajo el Vatnajökull, con río caliente dentro",
 "aldeyjarfoss": "Basalto negro columnado y agua glaciar turquesa",
 "hrafntinnusker": "Fumarolas, neveros y obsidiana a 1.050 m",
 "alftavatn": "Lago del segundo día del Laugavegur, con glaciares detrás",
 "emstrur": "El cañón de Markarfljót visto desde el desierto negro",
 "fimmvorduhals": "25 km entre dos glaciares por los cráteres de 2010",
 "studlagil": "Cañón de columnas de basalto y agua turquesa del Jökla",
 "hengifoss": "128 m con franjas rojas de arcilla entre capas de lava",
 "seydisfjordur": "Calle arcoíris, iglesia azul y cascada al fondo del fiordo",
 "storurd": "Bloques gigantes y lagunas turquesa bajo los Dyrfjöll",
 "vok": "Piscinas flotando en el lago Urriðavatn, agua potable caliente",
 "mjoifjordur": "Fiordo de 18 km con la cascada escalonada de Klifbrekkufossar",
 "djupivogur": "Pueblo pesquero bajo la pirámide del Búlandstindur",
 "dettifoss": "193 m³/s: la cascada más potente de Europa",
 "selfoss_north": "Cortina ancha de saltos un kilómetro antes de Dettifoss",
 "asbyrgi": "Cañón en forma de herradura de 100 m con bosque dentro",
 "hljodaklettar": "Columnas de basalto retorcidas en todas las direcciones",
 "myvatn": "Lago de pseudocráteres, aves y agua geotermal",
 "dimmuborgir": "Laberinto de arcos y torres de lava",
 "hverir": "Solfataras, barro burbujeante y olor a azufre al pie del Námafjall",
 "krafla": "El cráter Víti con su lago azul dentro de una zona activa",
 "grjotagja": "Cueva con manantial a 45 °C (baño prohibido, vista permitida)",
 "godafoss": "12 m de altura y 30 de ancho, la cascada de los dioses",
 "husavik": "Capital europea de las ballenas: jorobadas casi cada salida",
 "siglufjordur": "Antiguo puerto del arenque encajado entre montañas",
 "hvitserkur": "Arco de 15 m que parece un troll bebiendo del mar",
 "kolugljufur": "Cañón con cascadas visto desde un puente de carretera",
 "vatnsnes": "Colonias de focas comunes desde la orilla",
 "akureyri": "La capital del norte, con la única ducha decente en 300 km",
 "grettislaug": "Poza de piedra a 39 °C al borde del Skagafjörður",
 "kirkjufell": "463 m con forma de flecha y las cascadas de Kirkjufellsfoss delante",
 "snaefellsjokull": "Volcán con glaciar encima, la entrada al centro de la Tierra de Verne",
 "djupalonssandur": "Playa de guijarros negros con restos de un pesquero inglés",
 "arnarstapi": "Acantilados perforados y el arco de Gatklettur",
 "londrangar": "Dos agujas de basalto de 75 m saliendo del mar",
 "svortuloft": "Faro naranja sobre acantilados verticales y arcos de lava",
 "ytritunga": "Playa donde las focas se tumban a diario con marea baja",
 "berserkjahraun": "Campo de lava cubierto de musgo de 4.000 años",
 "budir": "Iglesia de madera negra sola en un campo de lava",
 "hraunfossar": "Mil chorros saliendo directamente del borde del campo de lava",
 "deildartunguhver": "El manantial más caudaloso de Europa: 180 l/s a 97 °C",
 "glymur": "198 m de caída en un cañón con nidos de aves marinas",
 "vidgelmir": "El mayor tubo de lava del país, 1.585 m con hielo dentro",
 "dynjandi": "100 m en abanico, con cinco cascadas menores debajo",
 "latrabjarg": "14 km de acantilado y frailecillos a un metro sin miedo",
 "raudasandur": "Kilómetros de arena rosa y dorada frente al Snæfellsjökull",
 "hornstrandir": "Reserva sin carreteras ni habitantes, solo barco y botas",
 "hornbjarg": "534 m de pared vertical y medio millón de aves",
 "djupavik": "Fábrica de arenque abandonada en el fiordo más solitario",
 "krossneslaug": "Piscina de 1954 con el Ártico rompiendo a diez metros",
 "drangsnes": "Tres bañeras calientes al borde del mar, gratis",
 "isafjordur": "Capital de los Westfjords y puerto para Hornstrandir",
 "arnarfjordur": "El fiordo más ancho del noroeste, con montañas de mesa",
 "arcticfox": "El único mamífero terrestre nativo de Islandia",
 "reykjadalur": "Río a 38 °C tras 3 km de subida entre fumarolas",
 "seltun": "Barro amarillo y azul burbujeando junto a la pasarela",
 "kleifarvatn": "Lago de 97 m de profundidad sin desagüe visible",
 "brimketill": "Bañera de lava tallada por el oleaje del Atlántico",
 "fagradalsfjall": "Lava reciente todavía tibia en algunos puntos",
 "bluelagoon": "Agua lechosa a 38 °C a diez minutos del aeropuerto",
 "skylagoon": "Reykjavík: puerto viejo, Harpa y baño de borde infinito",
 "heimaey": "Isla con volcán de 1973 y 900.000 frailecillos en verano",
 "storhofdi": "El mirador de frailecillos más grande del Atlántico Norte",
 "solheimasandur": "Fuselaje de un DC-3 de la marina en la arena negra",
 "svinafellsjokull": "Lengua del Vatnajökull para andar con crampones",
 "icelandichorse": "Cinco marchas y mil años sin cruces con otras razas",
 "midnightsun": "En junio el sol roza el horizonte y vuelve a subir",
 "campervan": "Casa, cocina y transporte en el mismo trasto",
 "ringroad": "1.332 km de asfalto que dan la vuelta a la isla",
 "froad": "Pistas de montaña con vados: 4x4 y sentido común",
}

# ------------------------------------------------- ajustes finales de paradas
# Fauna con ficha propia y correcciones donde el material fotográfico real
# no correspondía al sitio (Diamond Beach queda dentro de Jökulsárlón).
NOMBRES_EXTRA = {
    "reykjavik": "Reykjavík",
    "frailecillos": "Frailecillos",
    "focas": "Focas",
    "ballenas": "Ballenas jorobadas",
}
TAGS.update({
    "reykjavik": "Hallgrímskirkja, el puerto viejo y la Harpa en una mañana",
    "frailecillos": "De mediados de abril a primeros de agosto; en junio están criando",
    "focas": "Focas comunes y grises, visibles desde la orilla con marea baja",
    "ballenas": "Jorobadas de mayo a septiembre; el pico es junio y julio",
    "grettislaug": "Poza de piedra a 39 °C frente a la isla de Drangey",
    "vatnsnes": "Costa de focas y el arco de Hvítserkur al final",
    "storhofdi": "El mirador del sur de Heimaey, azotado por el viento",
})

_DROP = {"diamondbeach"}
_RENAME = {"skylagoon": "reykjavik"}
_AFTER = {"vatnsnes": "focas", "ytritunga": "focas", "husavik": "ballenas",
          "latrabjarg": "frailecillos", "dyrholaey": "frailecillos", "storhofdi": "frailecillos"}
for _r in ROUTES:
    for _d in _r["dias_detalle"]:
        _s = [_RENAME.get(x, x) for x in _d["stops"] if x not in _DROP]
        _out = []
        for _x in _s:
            _out.append(_x)
            _extra = _AFTER.get(_x)
            if _extra and _extra not in _s:
                _out.append(_extra)
        _d["stops"] = _out
